// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/ironcore-dev/ipam/api/ipam/v1alpha1"
	ipamv1alpha1 "github.com/ironcore-dev/ipam/clientgo/applyconfiguration/ipam/v1alpha1"
	scheme "github.com/ironcore-dev/ipam/clientgo/ipam/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IPsGetter has a method to return a IPInterface.
// A group's client should implement this interface.
type IPsGetter interface {
	IPs(namespace string) IPInterface
}

// IPInterface has methods to work with IP resources.
type IPInterface interface {
	Create(ctx context.Context, iP *v1alpha1.IP, opts v1.CreateOptions) (*v1alpha1.IP, error)
	Update(ctx context.Context, iP *v1alpha1.IP, opts v1.UpdateOptions) (*v1alpha1.IP, error)
	UpdateStatus(ctx context.Context, iP *v1alpha1.IP, opts v1.UpdateOptions) (*v1alpha1.IP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.IP, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.IPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IP, err error)
	Apply(ctx context.Context, iP *ipamv1alpha1.IPApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.IP, err error)
	ApplyStatus(ctx context.Context, iP *ipamv1alpha1.IPApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.IP, err error)
	IPExpansion
}

// iPs implements IPInterface
type iPs struct {
	client rest.Interface
	ns     string
}

// newIPs returns a IPs
func newIPs(c *IpamV1alpha1Client, namespace string) *iPs {
	return &iPs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iP, and returns the corresponding iP object, and an error if there is any.
func (c *iPs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IP, err error) {
	result = &v1alpha1.IP{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ips").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IPs that match those selectors.
func (c *iPs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IPList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IPList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iPs.
func (c *iPs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a iP and creates it.  Returns the server's representation of the iP, and an error, if there is any.
func (c *iPs) Create(ctx context.Context, iP *v1alpha1.IP, opts v1.CreateOptions) (result *v1alpha1.IP, err error) {
	result = &v1alpha1.IP{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(iP).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a iP and updates it. Returns the server's representation of the iP, and an error, if there is any.
func (c *iPs) Update(ctx context.Context, iP *v1alpha1.IP, opts v1.UpdateOptions) (result *v1alpha1.IP, err error) {
	result = &v1alpha1.IP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ips").
		Name(iP.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(iP).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *iPs) UpdateStatus(ctx context.Context, iP *v1alpha1.IP, opts v1.UpdateOptions) (result *v1alpha1.IP, err error) {
	result = &v1alpha1.IP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ips").
		Name(iP.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(iP).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the iP and deletes it. Returns an error if one occurs.
func (c *iPs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ips").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iPs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ips").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched iP.
func (c *iPs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IP, err error) {
	result = &v1alpha1.IP{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ips").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied iP.
func (c *iPs) Apply(ctx context.Context, iP *ipamv1alpha1.IPApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.IP, err error) {
	if iP == nil {
		return nil, fmt.Errorf("iP provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(iP)
	if err != nil {
		return nil, err
	}
	name := iP.Name
	if name == nil {
		return nil, fmt.Errorf("iP.Name must be provided to Apply")
	}
	result = &v1alpha1.IP{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("ips").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *iPs) ApplyStatus(ctx context.Context, iP *ipamv1alpha1.IPApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.IP, err error) {
	if iP == nil {
		return nil, fmt.Errorf("iP provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(iP)
	if err != nil {
		return nil, err
	}

	name := iP.Name
	if name == nil {
		return nil, fmt.Errorf("iP.Name must be provided to Apply")
	}

	result = &v1alpha1.IP{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("ips").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
