// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IPListerExpansion allows custom methods to be added to
// IPLister.
type IPListerExpansion interface{}

// IPNamespaceListerExpansion allows custom methods to be added to
// IPNamespaceLister.
type IPNamespaceListerExpansion interface{}

// NetworkListerExpansion allows custom methods to be added to
// NetworkLister.
type NetworkListerExpansion interface{}

// NetworkNamespaceListerExpansion allows custom methods to be added to
// NetworkNamespaceLister.
type NetworkNamespaceListerExpansion interface{}

// NetworkCounterListerExpansion allows custom methods to be added to
// NetworkCounterLister.
type NetworkCounterListerExpansion interface{}

// NetworkCounterNamespaceListerExpansion allows custom methods to be added to
// NetworkCounterNamespaceLister.
type NetworkCounterNamespaceListerExpansion interface{}

// SubnetListerExpansion allows custom methods to be added to
// SubnetLister.
type SubnetListerExpansion interface{}

// SubnetNamespaceListerExpansion allows custom methods to be added to
// SubnetNamespaceLister.
type SubnetNamespaceListerExpansion interface{}
