// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/ironcore-dev/ipam/clientgo/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// IPs returns a IPInformer.
	IPs() IPInformer
	// Networks returns a NetworkInformer.
	Networks() NetworkInformer
	// NetworkCounters returns a NetworkCounterInformer.
	NetworkCounters() NetworkCounterInformer
	// Subnets returns a SubnetInformer.
	Subnets() SubnetInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// IPs returns a IPInformer.
func (v *version) IPs() IPInformer {
	return &iPInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Networks returns a NetworkInformer.
func (v *version) Networks() NetworkInformer {
	return &networkInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NetworkCounters returns a NetworkCounterInformer.
func (v *version) NetworkCounters() NetworkCounterInformer {
	return &networkCounterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Subnets returns a SubnetInformer.
func (v *version) Subnets() SubnetInformer {
	return &subnetInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
