// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	ipamv1alpha1 "github.com/onmetal/ipam/api/ipam/v1alpha1"
	internalinterfaces "github.com/onmetal/ipam/clientgo/informers/internalinterfaces"
	ipam "github.com/onmetal/ipam/clientgo/ipam"
	v1alpha1 "github.com/onmetal/ipam/clientgo/listers/ipam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkCounterInformer provides access to a shared informer and lister for
// NetworkCounters.
type NetworkCounterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NetworkCounterLister
}

type networkCounterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNetworkCounterInformer constructs a new informer for NetworkCounter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNetworkCounterInformer(client ipam.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNetworkCounterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNetworkCounterInformer constructs a new informer for NetworkCounter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNetworkCounterInformer(client ipam.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().NetworkCounters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().NetworkCounters(namespace).Watch(context.TODO(), options)
			},
		},
		&ipamv1alpha1.NetworkCounter{},
		resyncPeriod,
		indexers,
	)
}

func (f *networkCounterInformer) defaultInformer(client ipam.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNetworkCounterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *networkCounterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ipamv1alpha1.NetworkCounter{}, f.defaultInformer)
}

func (f *networkCounterInformer) Lister() v1alpha1.NetworkCounterLister {
	return v1alpha1.NewNetworkCounterLister(f.Informer().GetIndexer())
}
