// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/ironcore-dev/ipam/api/ipam/v1alpha1"
	ipamv1alpha1 "github.com/ironcore-dev/ipam/clientgo/applyconfiguration/ipam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkCounters implements NetworkCounterInterface
type FakeNetworkCounters struct {
	Fake *FakeIpamV1alpha1
	ns   string
}

var networkcountersResource = v1alpha1.SchemeGroupVersion.WithResource("networkcounters")

var networkcountersKind = v1alpha1.SchemeGroupVersion.WithKind("NetworkCounter")

// Get takes name of the networkCounter, and returns the corresponding networkCounter object, and an error if there is any.
func (c *FakeNetworkCounters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NetworkCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkcountersResource, c.ns, name), &v1alpha1.NetworkCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkCounter), err
}

// List takes label and field selectors, and returns the list of NetworkCounters that match those selectors.
func (c *FakeNetworkCounters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NetworkCounterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkcountersResource, networkcountersKind, c.ns, opts), &v1alpha1.NetworkCounterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkCounterList{ListMeta: obj.(*v1alpha1.NetworkCounterList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkCounterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkCounters.
func (c *FakeNetworkCounters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkcountersResource, c.ns, opts))

}

// Create takes the representation of a networkCounter and creates it.  Returns the server's representation of the networkCounter, and an error, if there is any.
func (c *FakeNetworkCounters) Create(ctx context.Context, networkCounter *v1alpha1.NetworkCounter, opts v1.CreateOptions) (result *v1alpha1.NetworkCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkcountersResource, c.ns, networkCounter), &v1alpha1.NetworkCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkCounter), err
}

// Update takes the representation of a networkCounter and updates it. Returns the server's representation of the networkCounter, and an error, if there is any.
func (c *FakeNetworkCounters) Update(ctx context.Context, networkCounter *v1alpha1.NetworkCounter, opts v1.UpdateOptions) (result *v1alpha1.NetworkCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkcountersResource, c.ns, networkCounter), &v1alpha1.NetworkCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkCounter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkCounters) UpdateStatus(ctx context.Context, networkCounter *v1alpha1.NetworkCounter, opts v1.UpdateOptions) (*v1alpha1.NetworkCounter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(networkcountersResource, "status", c.ns, networkCounter), &v1alpha1.NetworkCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkCounter), err
}

// Delete takes name of the networkCounter and deletes it. Returns an error if one occurs.
func (c *FakeNetworkCounters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(networkcountersResource, c.ns, name, opts), &v1alpha1.NetworkCounter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkCounters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkcountersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkCounterList{})
	return err
}

// Patch applies the patch and returns the patched networkCounter.
func (c *FakeNetworkCounters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NetworkCounter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkcountersResource, c.ns, name, pt, data, subresources...), &v1alpha1.NetworkCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkCounter), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied networkCounter.
func (c *FakeNetworkCounters) Apply(ctx context.Context, networkCounter *ipamv1alpha1.NetworkCounterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NetworkCounter, err error) {
	if networkCounter == nil {
		return nil, fmt.Errorf("networkCounter provided to Apply must not be nil")
	}
	data, err := json.Marshal(networkCounter)
	if err != nil {
		return nil, err
	}
	name := networkCounter.Name
	if name == nil {
		return nil, fmt.Errorf("networkCounter.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkcountersResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.NetworkCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkCounter), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeNetworkCounters) ApplyStatus(ctx context.Context, networkCounter *ipamv1alpha1.NetworkCounterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NetworkCounter, err error) {
	if networkCounter == nil {
		return nil, fmt.Errorf("networkCounter provided to Apply must not be nil")
	}
	data, err := json.Marshal(networkCounter)
	if err != nil {
		return nil, err
	}
	name := networkCounter.Name
	if name == nil {
		return nil, fmt.Errorf("networkCounter.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkcountersResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.NetworkCounter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkCounter), err
}
