apiVersion: ipam.ironcore.dev/v1alpha1
kind: Subnet
metadata:
  name: ipv6-child-cidr-subnet-sample
spec:
  cidr: "fd34:5d8f:e75e:f3a2::/68"
  parentSubnetName: "ipv6-parent-cidr-subnet-sample"
  networkName: network-sample
  regions:
    - name: euw
      availabilityZones:
        - a
        - b