apiVersion: ipam.ironcore.dev/v1alpha1
kind: Subnet
metadata:
  name: ipv4-parent-cidr-subnet-sample
spec:
  cidr: "10.0.0.0/8"
  networkName: network-sample
  regions:
    - name: euw
      availabilityZones:
        - a
        - b
        - c