
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ipam-onmetal-de-v1alpha1-ip
  failurePolicy: Fail
  name: vip.kb.io
  rules:
  - apiGroups:
    - ipam.onmetal.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - ips
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ipam-onmetal-de-v1alpha1-network
  failurePolicy: Fail
  name: vnetwork.kb.io
  rules:
  - apiGroups:
    - ipam.onmetal.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networks
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ipam-onmetal-de-v1alpha1-subnet
  failurePolicy: Fail
  name: vsubnet.kb.io
  rules:
  - apiGroups:
    - ipam.onmetal.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - subnets
  sideEffects: None
