// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package internal

import (
	"fmt"
	"sync"

	typed "sigs.k8s.io/structured-merge-diff/v4/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.CIDR
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.IP
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.IPSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.IPStatus
      default: {}
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.IPAddr
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.IPSpec
  map:
    fields:
    - name: consumer
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.ResourceReference
    - name: ip
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.IPAddr
    - name: subnet
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.IPStatus
  map:
    fields:
    - name: message
      type:
        scalar: string
    - name: reserved
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.IPAddr
    - name: state
      type:
        scalar: string
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.Network
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkStatus
      default: {}
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkCounter
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkCounterSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkCounterStatus
      default: {}
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkCounterSpec
  map:
    fields:
    - name: vacant
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkIDInterval
          elementRelationship: atomic
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkCounterStatus
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkID
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkIDInterval
  map:
    fields:
    - name: begin
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkID
    - name: end
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkID
    - name: exact
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkID
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkSpec
  map:
    fields:
    - name: description
      type:
        scalar: string
    - name: id
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkID
    - name: type
      type:
        scalar: string
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkStatus
  map:
    fields:
    - name: ipv4Capacity
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
      default: {}
    - name: ipv4Ranges
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.CIDR
          elementRelationship: atomic
    - name: ipv6Capacity
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
      default: {}
    - name: ipv6Ranges
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.CIDR
          elementRelationship: atomic
    - name: message
      type:
        scalar: string
    - name: reserved
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.NetworkID
    - name: state
      type:
        scalar: string
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.Region
  map:
    fields:
    - name: availabilityZones
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
      default: ""
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.ResourceReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
      default: ""
    - name: name
      type:
        scalar: string
      default: ""
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.Subnet
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.SubnetSpec
      default: {}
    - name: status
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.SubnetStatus
      default: {}
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.SubnetSpec
  map:
    fields:
    - name: capacity
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: cidr
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.CIDR
    - name: consumer
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.ResourceReference
    - name: network
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
    - name: parentSubnet
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
    - name: prefixBits
      type:
        scalar: numeric
    - name: regions
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.Region
          elementRelationship: atomic
- name: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.SubnetStatus
  map:
    fields:
    - name: capacity
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
      default: {}
    - name: capacityLeft
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
      default: {}
    - name: locality
      type:
        scalar: string
    - name: message
      type:
        scalar: string
    - name: prefixBits
      type:
        scalar: numeric
    - name: reserved
      type:
        namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.CIDR
    - name: state
      type:
        scalar: string
    - name: type
      type:
        scalar: string
    - name: vacant
      type:
        list:
          elementType:
            namedType: com.github.ironcore-dev.ipam.api.ipam.v1alpha1.CIDR
          elementRelationship: atomic
- name: io.k8s.api.core.v1.LocalObjectReference
  map:
    fields:
    - name: name
      type:
        scalar: string
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.api.resource.Quantity
  scalar: untyped
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        scalar: string
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
      default: {}
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
      default: ""
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
      default: ""
    - name: name
      type:
        scalar: string
      default: ""
    - name: uid
      type:
        scalar: string
      default: ""
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
