name: 'Assign size labels to PRs'

on: [workflow_dispatch, pull_request]

jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@v0.5.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
